name: flutter_reacton
description: >
  Flutter widgets and bindings for the Reacton state management library.
  Provides ReactonScope, ReactonBuilder, context.watch(), and more.
version: 0.1.2
homepage: https://github.com/sitharaj88/reacton
repository: https://github.com/sitharaj88/reacton
issue_tracker: https://github.com/sitharaj88/reacton/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  reacton: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
