name: reacton_devtools
description: >
  Flutter DevTools extension for Reacton. Provides reactive graph visualization,
  reacton inspector, timeline view, and state branching UI.
version: 0.1.1
homepage: https://github.com/sitharaj88/reacton
repository: https://github.com/sitharaj88/reacton
issue_tracker: https://github.com/sitharaj88/reacton/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.1.0
  reacton: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
