name: reacton
description: >
  A novel reactive graph engine for Dart. Fine-grained state management with
  reactons, computed values, effects, state branching, time-travel, and more.
version: 0.1.0
homepage: https://github.com/sitharaj88/reacton
repository: https://github.com/sitharaj88/reacton
issue_tracker: https://github.com/sitharaj88/reacton/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
