name: reacton_test
description: >
  Testing utilities for Reacton state management. Provides TestReactonStore,
  reacton mocks, effect trackers, and widget test helpers.
version: 0.1.1
homepage: https://github.com/sitharaj88/reacton
repository: https://github.com/sitharaj88/reacton
issue_tracker: https://github.com/sitharaj88/reacton/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  reacton: ^0.1.0
  flutter_reacton: ^0.1.0
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
